"""Тесты автогена index.md/log.md и штамповки дат (ADR-0011, шаг 2)."""

from datetime import date
from pathlib import Path

from svarog_harness.memory.apply import apply_change, preview_content
from svarog_harness.memory.change import MemoryChangeRequest, MemoryOperation
from svarog_harness.memory.wiki import append_log, log_entry, regenerate_index, render_index

_PAGE = """\
---
name: AnimateYou
slug: animateyou
summary: бот генерации медиа
status: active
---
Описание.
"""


def _create_project(
    root: Path, slug: str, *, status: str = "active", today: date, summary: str | None = None
) -> None:
    content = _PAGE.replace("slug: animateyou", f"slug: {slug}").replace(
        "status: active", f"status: {status}"
    )
    if summary is not None:
        content = content.replace("summary: бот генерации медиа", f"summary: {summary}")
    apply_change(
        root,
        MemoryChangeRequest(
            file=f"projects/{slug}/overview.md",
            operation=MemoryOperation.CREATE,
            content=content,
        ),
        today=today,
    )


def test_apply_stamps_dates_on_project_page(tmp_path: Path) -> None:
    _create_project(tmp_path, "animateyou", today=date(2026, 7, 10))
    text = (tmp_path / "projects/animateyou/overview.md").read_text(encoding="utf-8")
    assert "created: 2026-07-10" in text
    assert "updated: 2026-07-10" in text


def test_apply_updates_updated_on_change(tmp_path: Path) -> None:
    _create_project(tmp_path, "animateyou", today=date(2026, 1, 1))
    apply_change(
        tmp_path,
        MemoryChangeRequest(
            file="projects/animateyou/overview.md",
            operation=MemoryOperation.APPEND,
            content="\nещё строка\n",
        ),
        today=date(2026, 7, 10),
    )
    text = (tmp_path / "projects/animateyou/overview.md").read_text(encoding="utf-8")
    assert "created: 2026-01-01" in text
    assert "updated: 2026-07-10" in text


def test_non_project_page_not_stamped(tmp_path: Path) -> None:
    apply_change(
        tmp_path,
        MemoryChangeRequest(
            file="user/profile.md", operation=MemoryOperation.CREATE, content="# Профиль\n"
        ),
        today=date(2026, 7, 10),
    )
    assert "updated:" not in (tmp_path / "user/profile.md").read_text(encoding="utf-8")


def test_preview_content_does_not_write(tmp_path: Path) -> None:
    req = MemoryChangeRequest(
        file="projects/x/overview.md", operation=MemoryOperation.CREATE, content=_PAGE
    )
    assert "name: AnimateYou" in preview_content(tmp_path, req)
    assert not (tmp_path / "projects/x/overview.md").exists()


def test_render_index_lists_active_and_archived(tmp_path: Path) -> None:
    _create_project(tmp_path, "animateyou", today=date(2026, 7, 10))
    _create_project(tmp_path, "oldproj", status="archived", today=date(2026, 1, 1))
    apply_change(
        tmp_path,
        MemoryChangeRequest(
            file="user/profile.md", operation=MemoryOperation.CREATE, content="# Профиль\n"
        ),
    )
    index = render_index(tmp_path)
    assert "AUTOGENERATED" in index
    assert "[AnimateYou](projects/animateyou/overview.md)" in index
    assert "## Проекты (архив)" in index
    assert "projects/oldproj/overview.md" in index
    assert "## Пользователь" in index


def test_render_index_empty_projects(tmp_path: Path) -> None:
    assert "_(пока нет проектов)_" in render_index(tmp_path)


def test_render_index_lists_sources(tmp_path: Path) -> None:
    (tmp_path / "sources" / "animateyou").mkdir(parents=True)
    (tmp_path / "sources/animateyou/spec.md").write_text("raw", encoding="utf-8")
    index = render_index(tmp_path)
    assert "## Источники" in index
    assert "[animateyou/spec.md](sources/animateyou/spec.md)" in index


def test_render_index_no_sources_section_when_empty(tmp_path: Path) -> None:
    assert "## Источники" not in render_index(tmp_path)


def test_regenerate_index_writes_file(tmp_path: Path) -> None:
    _create_project(tmp_path, "animateyou", today=date(2026, 7, 10))
    regenerate_index(tmp_path)
    assert "animateyou" in (tmp_path / "index.md").read_text(encoding="utf-8")


def test_log_entry_format() -> None:
    entry = log_entry(
        operation="create",
        path="projects/x/overview.md",
        run_id="abcdef1234",
        when=date(2026, 7, 10),
    )
    assert entry == "## [2026-07-10] create | projects/x/overview.md | run abcdef12"


def test_append_log_is_append_only(tmp_path: Path) -> None:
    append_log(tmp_path, ["## [2026-07-10] create | a | run x"])
    append_log(tmp_path, ["## [2026-07-11] append | a | run y"])
    text = (tmp_path / "log.md").read_text(encoding="utf-8")
    assert text.count("## [") == 2
    assert text.index("2026-07-10") < text.index("2026-07-11")


def test_render_index_caps_line_length(tmp_path: Path) -> None:
    """ADR-0015 §1.5: длинный summary укорачивается — строка индекса ~200 символов."""
    _create_project(tmp_path, "wordy", today=date(2026, 7, 10), summary="о" * 500)
    index = render_index(tmp_path)
    line = next(li for li in index.splitlines() if "wordy" in li)
    assert len(line) <= 200
    assert line.endswith("…") or "…" in line


def test_render_index_caps_total_lines(tmp_path: Path) -> None:
    for i in range(30):
        _create_project(tmp_path, f"proj{i:02d}", today=date(2026, 7, 10))
    index = render_index(tmp_path, max_lines=10)
    lines = index.splitlines()
    assert len(lines) <= 10
    assert "и ещё" in lines[-1]
    assert "read_memory" in lines[-1]


def test_render_index_no_tail_when_under_limit(tmp_path: Path) -> None:
    _create_project(tmp_path, "single", today=date(2026, 7, 10))
    assert "и ещё" not in render_index(tmp_path)
