"""initial schema

Revision ID: a181df665c80
Revises:
Create Date: 2026-07-08 14:12:17.149762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a181df665c80"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sessions",
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "runs",
        sa.Column("session_id", sa.String(length=32), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "pending",
                "running",
                "waiting_approval",
                "suspended",
                "completed",
                "failed",
                "cancelled",
                name="runstate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("task", sa.Text(), nullable=False),
        sa.Column("autonomy", sa.String(length=32), nullable=False),
        sa.Column("iterations", sa.Integer(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["session_id"], ["sessions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_session_id"), ["session_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_state"), ["state"], unique=False)

    op.create_table(
        "artifacts",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("path", sa.String(length=1024), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_artifacts_run_id"), ["run_id"], unique=False)

    op.create_table(
        "check_results",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("check_name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "passed",
                "failed",
                "error",
                "skipped",
                name="checkstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("check_results", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_check_results_run_id"), ["run_id"], unique=False)

    op.create_table(
        "checkpoints",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_checkpoints_run_id"), ["run_id"], unique=False)
        batch_op.create_index("ix_checkpoints_run_iteration", ["run_id", "iteration"], unique=False)

    op.create_table(
        "error_events",
        sa.Column("run_id", sa.String(length=32), nullable=True),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("error_events", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_error_events_run_id"), ["run_id"], unique=False)

    op.create_table(
        "memory_queue",
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "applied",
                "failed",
                name="memorychangestatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("change", sa.JSON(), nullable=False),
        sa.Column("source_run_id", sa.String(length=32), nullable=True),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column("commit_sha", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["source_run_id"], ["runs.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("memory_queue", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_memory_queue_status"), ["status"], unique=False)

    op.create_table(
        "messages",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("index_in_run", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("content", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "index_in_run"),
    )
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_messages_run_id"), ["run_id"], unique=False)

    op.create_table(
        "skill_loads",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("skill_name", sa.String(length=128), nullable=False),
        sa.Column("skill_version", sa.String(length=64), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("skill_loads", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_skill_loads_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_skill_loads_skill_name"), ["skill_name"], unique=False)

    op.create_table(
        "tool_calls",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("message_id", sa.String(length=32), nullable=True),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column("risk_level", sa.String(length=32), nullable=True),
        sa.Column("policy_decision", sa.String(length=32), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running",
                "succeeded",
                "failed",
                "denied",
                name="toolcallstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_tool_calls_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_tool_calls_tool_name"), ["tool_name"], unique=False)

    op.create_table(
        "approvals",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("tool_call_id", sa.String(length=32), nullable=True),
        sa.Column("action_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "approved",
                "denied",
                "expired",
                name="approvalstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("decided_at", sa.DateTime(), nullable=True),
        sa.Column("decided_by", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tool_call_id"], ["tool_calls.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_approvals_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_approvals_status"), ["status"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("approvals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_approvals_status"))
        batch_op.drop_index(batch_op.f("ix_approvals_run_id"))

    op.drop_table("approvals")
    with op.batch_alter_table("tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_tool_calls_tool_name"))
        batch_op.drop_index(batch_op.f("ix_tool_calls_run_id"))

    op.drop_table("tool_calls")
    with op.batch_alter_table("skill_loads", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_skill_loads_skill_name"))
        batch_op.drop_index(batch_op.f("ix_skill_loads_run_id"))

    op.drop_table("skill_loads")
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_messages_run_id"))

    op.drop_table("messages")
    with op.batch_alter_table("memory_queue", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_memory_queue_status"))

    op.drop_table("memory_queue")
    with op.batch_alter_table("error_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_error_events_run_id"))

    op.drop_table("error_events")
    with op.batch_alter_table("checkpoints", schema=None) as batch_op:
        batch_op.drop_index("ix_checkpoints_run_iteration")
        batch_op.drop_index(batch_op.f("ix_checkpoints_run_id"))

    op.drop_table("checkpoints")
    with op.batch_alter_table("check_results", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_check_results_run_id"))

    op.drop_table("check_results")
    with op.batch_alter_table("artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_artifacts_run_id"))

    op.drop_table("artifacts")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_state"))
        batch_op.drop_index(batch_op.f("ix_runs_session_id"))

    op.drop_table("runs")
    op.drop_table("sessions")
    # ### end Alembic commands ###
