#!/usr/bin/env bash
# Воспроизводимый запуск сценария симуляции на opencode + glm-5.2 + docker.
#
# Инкапсулирует рецепт, отработанный в retest-прогонах 2026-07-29:
#   - external executor, adapter=opencode
#   - модель z-ai/glm-5.2 через OpenRouter
#   - sandbox: docker (образ svarog/agent-opencode:latest)
#   - память — собственный git-репо с seed-коммитом
#   - workspace — отдельный одноразовый git-репо с project-level svarog.yaml
#
# Использование:
#   ./simulation/run-retest.sh <scenario-id> [seed-dir]
#     scenario-id — S2, S4, S7, S9, S18, S24, S25, S26, S27, …
#     seed-dir    — опц. каталог с baseline-файлами памяти (user/profile.md,
#                   projects/<slug>/overview.md …); кладётся в память до seed-коммита
#
# Переменные окружения:
#   SVAROG_REPO     — корень репозитория (по умолчанию git rev-parse --show-toplevel)
#   SECRETS_PATH    — путь к secrets.json (по умолчанию ~/.svarog/secrets.json)
#   MODEL           — модель opencode (по умолчанию z-ai/glm-5.2)
#   SIM_ROOT        — куда класть сим-директории (по умолчанию /tmp)
#   KEEP_SIM        — если=1, не удалять сим-директорию в конце (по умолчанию 0)
#
# Выход: путь к созданной сим-директории в stdout (для подхвата вызывающим).
# Логи: $SIM/run.log (агрегированный), $SIM/run1.log, $SIM/run2.log (по ходам).
set -euo pipefail

SCENARIO_ID="${1:?укажи scenario-id, например S18}"
SEED_DIR="${2:-}"
SVAROG_REPO="${SVAROG_REPO:-$(git rev-parse --show-toplevel)}"
SECRETS_PATH="${SECRETS_PATH:-$HOME/.svarog/secrets.json}"
MODEL="${MODEL:-z-ai/glm-5.2}"
SIM_ROOT="${SIM_ROOT:-/tmp}"
KEEP_SIM="${KEEP_SIM:-0}"

SLUG="re${SCENARIO_ID}"
SIM="$(mktemp -d "${SIM_ROOT}/svarog-${SLUG}-XXXXXX")"
mkdir -p "$SIM/state" "$SIM/ws"

# 1) Память как собственный git-репо с seed-коммитом
mkdir -p "$SIM/memory/user" "$SIM/memory/projects" "$SIM/memory/decisions"
printf '# Профиль\n' > "$SIM/memory/user/profile.md"
if [[ -n "$SEED_DIR" && -d "$SEED_DIR" ]]; then
  cp -R "$SEED_DIR/." "$SIM/memory/" 2>/dev/null || true
fi
printf '# Индекс памяти\n<!-- AUTOGENERATED -->\n' > "$SIM/memory/index.md"
git -C "$SIM/memory" init -q
git -C "$SIM/memory" add -A
git -C "$SIM/memory" -c user.name=Sim -c user.email=sim@localhost commit -qm seed

# 2) Workspace — одноразовый git-репо с project-level конфигом
git -C "$SIM/ws" init -q
printf 'scratch\n' > "$SIM/ws/README.md"

cat > "$SIM/ws/svarog.yaml" <<YAML
models:
  default: local
  providers:
    local:
      type: openai-compatible
      base_url: https://openrouter.ai/api/v1
      model: deepseek/deepseek-v4-flash
      api_key_ref: PROVIDER_API_KEY
runtime:
  autonomy: yolo
sandbox:
  type: docker
memory:
  path: $SIM/memory
storage:
  db_path: $SIM/state/svarog.db
secrets:
  path: $SECRETS_PATH
skills:
  paths: []
policies:
  protected_branches: [main, production]
executor:
  type: external
  external:
    adapter: opencode
    image: svarog/agent-opencode:latest
    base_url: https://openrouter.ai/api
    model: $MODEL
    auth: api-key
    api_key_ref: PROVIDER_API_KEY
    enforcement: containment
YAML

git -C "$SIM/ws" add -A
git -C "$SIM/ws" -c user.name=Sim -c user.email=sim@localhost commit -qm init

echo "SIM=$SIM" > "$SIM/sim.env"
echo "$SIM"
