"""Автоген навигационных файлов памяти-wiki: index.md и log.md (ADR-0011).

Индекс и лог ведёт код (не модель): единственный memory-writer вызывает
`regenerate_index`/`append_log` после применения заявок, под writer-локом.
Поскольку writer сериализован, регенерация из полного состояния всегда
консистентна — проблемы last-writer-wins для каталога не возникает.
"""

from datetime import date
from pathlib import Path

from svarog_harness.common.frontmatter import first_body_paragraph, split_frontmatter

_INDEX = "index.md"
_LOG = "log.md"
_AUTOGEN = "<!-- AUTOGENERATED — собирается из frontmatter страниц; не редактируйте вручную -->"

# active/paused показываем как рабочие, archived — отдельным разделом.
_ACTIVE_STATUSES = ("active", "paused")


def _project_pages(memory_dir: Path) -> list[dict[str, str]]:
    """frontmatter всех projects/*/overview.md как список полей-строк."""
    root = memory_dir / "projects"
    if not root.is_dir():
        return []
    pages: list[dict[str, str]] = []
    for overview in sorted(root.glob("*/overview.md")):
        try:
            frontmatter, _ = split_frontmatter(overview.read_text(encoding="utf-8"))
        except OSError:
            continue
        if not frontmatter:
            continue
        slug = overview.parent.name
        pages.append(
            {
                "name": str(frontmatter.get("name", slug)).strip() or slug,
                "slug": slug,
                "summary": str(frontmatter.get("summary", "")).strip(),
                "status": str(frontmatter.get("status", "")).strip().lower(),
                "updated": str(frontmatter.get("updated", "")).strip(),
                "path": f"projects/{slug}/overview.md",
            }
        )
    return pages


def _decision_pages(memory_dir: Path) -> list[tuple[str, str, str]]:
    """(заголовок, краткое, путь) для decisions/*.md."""
    root = memory_dir / "decisions"
    if not root.is_dir():
        return []
    out: list[tuple[str, str, str]] = []
    for md in sorted(root.glob("*.md")):
        try:
            text = md.read_text(encoding="utf-8")
        except OSError:
            continue
        title = md.stem
        for line in text.splitlines():
            if line.strip().startswith("#"):
                title = line.strip().lstrip("#").strip()
                break
        out.append((title, first_body_paragraph(text), f"decisions/{md.name}"))
    return out


def _source_files(memory_dir: Path) -> list[str]:
    """Относительные пути файлов raw-слоя sources/ (отсортированы)."""
    root = memory_dir / "sources"
    if not root.is_dir():
        return []
    return sorted(str(p.relative_to(memory_dir)) for p in root.rglob("*") if p.is_file())


def _project_line(page: dict[str, str]) -> str:
    meta = " · ".join(x for x in (page["status"], page["updated"]) if x)
    tail = f" — {page['summary']}" if page["summary"] else ""
    suffix = f" _({meta})_" if meta else ""
    return f"- [{page['name']}]({page['path']}){tail}{suffix}"


def render_index(memory_dir: Path) -> str:
    """Собрать текст index.md из текущего состояния памяти."""
    pages = _project_pages(memory_dir)
    active = sorted(
        (p for p in pages if p["status"] in _ACTIVE_STATUSES),
        key=lambda p: p["updated"],
        reverse=True,
    )
    archived = [p for p in pages if p["status"] == "archived"]
    lines = [f"# Индекс памяти\n{_AUTOGEN}", "", "## Проекты"]
    lines += [_project_line(p) for p in active] or ["_(пока нет проектов)_"]
    if archived:
        lines += ["", "## Проекты (архив)"]
        lines += [_project_line(p) for p in archived]
    decisions = _decision_pages(memory_dir)
    if decisions:
        lines += ["", "## Решения"]
        for title, summary, path in decisions:
            tail = f" — {summary}" if summary else ""
            lines.append(f"- [{title}]({path}){tail}")
    sources = _source_files(memory_dir)
    if sources:
        lines += ["", "## Источники"]
        for rel in sources:
            label = rel.removeprefix("sources/")
            lines.append(f"- [{label}]({rel})")
    if (memory_dir / "user" / "profile.md").exists():
        lines += ["", "## Пользователь", "- [Профиль](user/profile.md)"]
    return "\n".join(lines).rstrip("\n") + "\n"


def regenerate_index(memory_dir: Path) -> None:
    """Перезаписать index.md текущим состоянием (идемпотентно)."""
    (memory_dir / _INDEX).write_text(render_index(memory_dir), encoding="utf-8")


def log_entry(*, operation: str, path: str, run_id: str | None, when: date) -> str:
    """Строка журнала с парсимым префиксом: `## [YYYY-MM-DD] op | path | run id8`."""
    run = run_id[:8] if run_id else "-"
    return f"## [{when.isoformat()}] {operation} | {path} | run {run}"


def append_log(memory_dir: Path, entries: list[str]) -> None:
    """Дописать строки в log.md (append-only). Пустой список — no-op."""
    if not entries:
        return
    path = memory_dir / _LOG
    existing = path.read_text(encoding="utf-8") if path.exists() else "# Журнал памяти\n"
    if existing and not existing.endswith("\n"):
        existing += "\n"
    path.write_text(existing + "\n".join(entries) + "\n", encoding="utf-8")
